### ISSUE TITLE
Center mode broken when change the width of react-multi-carousel-item

### ISSUE THREAD

**Issue by plumest** [YIZHUANG/react-multi-carousel#272]
I want to create an infinity loop carousel with center mode and fix the width of the picture to not changing when resizing the browser.
So I add `centerMode={true}`, `infinite={true}`, and `itemClass="image-item"` to change the width of items like this

```css
.image-item {
    padding: 0 10px;
    width: 400px !important;
}
```

The problem is my picture does not place at the center and it even worse than before when it slides to the other ones.

This is my codesandbox link: https://codesandbox.io/s/react-multi-carousel-playground-forked-hrs0l?file=/components/Simple.js
