### ISSUE TITLE
Dragging is now working as expected on mobile (scroll issues)

### ISSUE THREAD

**Issue by salihkesepara** [YIZHUANG/react-multi-carousel#438]
When using it on mobile draggable is not working as expected. 

1. Go to Chrome browser
2. Open inspect
3. drag items to the right or left and then try to drag them up and down.

### **Current behavior**
All page scrolling
![Current](https://github.com/YIZHUANG/react-multi-carousel/assets/9534850/e2579961-9b8c-42cd-8e10-1c4e754b2999)

### **Expected behavior**
Just carousel items should be scroll
![Expected](https://github.com/YIZHUANG/react-multi-carousel/assets/9534850/f7ca1824-a36c-4ac7-a211-4efc9c2c5365)

**Comment by barrard** [comment]
I have the same issue. it is now not working.

**Comment by julievalet** [comment]
To try to fix this issue, I tried this:
```css
.react-multi-carousel-list {
    touch-action: pan-y pinch-zoom;
    overscroll-behavior-x: contain;
}
```

It seems to work in my desktop browser but not on my phone on iOS.
